# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DIARY APP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DIARY APP
  pod 'ProgressHUD'
  pod 'AlamofireObjectMapper'
  pod 'IQKeyboardManagerSwift'

end
